@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes company command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([else])
    :Check if contact exists in Connectify's data;
        if () then ([contact exists])
            :Check if company command is to remove or to add;
                if () then ([company command is to remove])
                    :Check if contact has existing company
                    attribute to remove;
                        if () then ([contact has existing company attribute])
                            :Remove company attribute from contact;
                        else ([else])
                            :Throw error message that there is no existing
                            company attribute to remove from contact;
                        endif
                else ([else])
                    :Add company attribute to contact;
                endif
        else ([else])
            :Throw contact does not exist CommandException;
        endif
else ([empty contact name specified])
    :Throw empty name CommandException;
endif
stop
@enduml
